### ISSUE TITLE
[Feature request] VSCode: Display errors above documentation

### ISSUE THREAD

**Issue by dorian-marchal** [elixir-lsp/elixir-ls#133]
<details>
<summary>Environment</summary>

* Elixir & Erlang versions (elixir --version): 
    ```
    Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

    Elixir 1.10.1 (compiled with Erlang/OTP 21)
    ```

* Operating system: __Ubuntu 18.04__

* Editor or IDE name (e.g. Emacs/VSCode): __VSCode__

* LSP Client name: __I'm not sure, is VSCode an "LSP" client?__

* If using VSCode, are you using "ElixirLS Fork: Elixir support and debugger" (note that it has "Fork" in the name)? __Yup__

</details>

### Feature request

When VSCode underlines a problem in my code (error or warning), I can hover it to see the error message. If the hovered module is documented, its documentation is shown first and I have to scroll all the way down to see the message (notice the scroll bar):

![Screenshot from 2020-02-18 21-44-04](https://user-images.githubusercontent.com/6225979/74776460-e2fd1e80-5297-11ea-9bfc-5a05aa3eb40c.png)

It would be nice to show the errors first.

Edit: I almost forgot: thanks for maintaining this fork. :heart:

**Comment by axelson** [comment]
This would be a good improvement, but I'm not sure if we can accomplish it here or in vscode-elixir-ls since I'm pretty sure that the documentation and the error are returned separately, so you'd probably have to raise an issue on VSCode itself. As a workaround in vscode you can open view->problems which will open a problems section at the bottom:

![screenshot-problem](https://user-images.githubusercontent.com/9973/74961880-edf8a180-53b2-11ea-9c9f-b8490580c24c.png)

**Comment by axelson** [comment]
I've been thinking about this some more and as far as I can tell we cannot do anything in ElixirLS to change this behavior, instead you'd have to file an issue on VSCode itself. Glad to re-open if there's something concrete we can do here though!
