### ISSUE TITLE
Idea: put a .gitignore in the .elixir_ls folder

### ISSUE THREAD

**Issue by mikl** [elixir-lsp/elixir-ls#206]
Just a small idea: when creating the .elixir_ls folder, add a .gitignore file inside it with this content:

```
*
```

Given that almost everyone uses Git and no one (presumably) wants to add their .elixir_ls folder to their Git history, it would save users from having to set up an ignore rule themselves.

(Copied from https://github.com/JakeBecker/elixir-ls/issues/193 )

**Comment by NobbZ** [comment]
I prefer to teach folks how to set up global ignore rules for local tooling, rather than making the tooling do the users job…

https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

Though, this makes me wonder, can't we use `XDG_CACHE_HOME` for the current `.elixir_ls`? Though then we would probably need a way for the LS to rebuild that projects cache without the user having to find it manually in its `XDG_CACHE_HOME` when users feel the necessity to purge it.

**Comment by mikl** [comment]
> I prefer to teach folks how to set up global ignore rules for local tooling, rather than making the tooling do the users job

One might ask what is less effort, having everyone who uses ElixirLS have to deal with this, or just solving the problem for them.

> this makes me wonder, can't we use XDG_CACHE_HOME for the current .elixir_ls

Not only does that make it hard to figure out how to purge it, there’s also lots of other fun problems associated. What happens if a user has multiple Elixir projects? What if he has multiple copies of the same project? What happens when XDG_CACHE_HOME is on a case-insensitive FS, but the code on a case-sensitive FS (That would be the case for me)? 

Co-locating the `.elixir_ls` folder with the source code sidesteps a raft of potential bugs. And if we could save everyone using ElixirLS a little hassle having to play around with .gitignore, I figure that would be worth it.

**Comment by axelson** [comment]
I think including a `.gitignore` like mentioned is a good idea. And it even ignores the `.gitignore` file as well which is great. Although it looks like there is no clear place where the `.elixir_ls` directory is created, so perhaps something like that should be added that will create the `.gitignore` file on startup.

**Comment by wingyplus** [comment]
I prototype this feature in the PR above by creating gitignore before trigger build because project dir living inside `Server` state and it's no clear place like @axelson said.
