### ISSUE TITLE
What's this project's goal?

### ISSUE THREAD

**Issue by edwardsmit** [elixir-lsp/elixir-ls#22]
Hi, I just stumbled upon this repo and wonder two things:
- What's this project its goal, or how is it different from Jake Becker's version?
- Why or when should I use this project instead of Jake Becker's version

KR,
Edward

**Comment by axelson** [comment]
Hi Edward, we should really add something about this to the README but here is our rationale:

This fork started while Jake Becker's version was inactive for an extended period of time. So we decided to start an active fork to merge dormant PR's and fix issues where possible. We also believe in an open and shared governance model to share the work instead of relying on one person to shoulder the whole burden. Since Jake Becker's version has become semi-active, this project is currently semi-dormant (but definitely accepting and merging PR's as well as including all upstream work).

I hope that helps to clear it up!

**Comment by edwardsmit** [comment]
Hi Jason, it's clear to me now.

Thanks.

**Comment by axelson** [comment]
Great, thanks!
