### ISSUE TITLE
Clarificaiton regarding completion response spec

### ISSUE THREAD

**Issue by akash-akya** [elixir-lsp/elixir-ls#27]
Currently, completion for module attributes returns `insertText` with `@` prefix removed.

ie. if the module have `@default_value` attribute. `@defa<cursor>` returns `defult_value` as insertText. 

From the spec `CompletionItem.insertText` should be complete text including `@`?

**Comment by axelson** [comment]
I do see that `insertText` is deprecated: https://github.com/microsoft/language-server-protocol/blame/56e4fc292c121118ac520c8a19688c85066ed0bb/specification.md#L2946 because
> 	* The `insertText` is subject to interpretation by the client side.
	 * Some tools might not take the string literally. For example
	 * VS Code when code complete is requested in this example `con<cursor position>`
	 * and a completion item with an `insertText` of `console` is provided it
	 * will only insert `sole`. Therefore it is recommended to use `textEdit` instead
	 * since it avoids additional client side interpretation.

Unfortunately elixir-ls does not yet support `textEdit`.

This is the response that I'm seeing:
```
%{
  "id" => 15,
  "jsonrpc" => "2.0",
  "result" => %{
    "isIncomplete" => false,
    "items" => [
      %{
        "detail" => "module attribute",
        "filterText" => "default_value",
        "insertText" => "default_value",
        "insertTextFormat" => 2,
        "kind" => 6,
        "label" => "@default_value",
        "sortText" => "00000000"
      }
    ]
  }
}
```

Which appears to work as expected in the two lsp editors that I tested (emacs lsp-mode and vscode). What editor are you using?

(Closing this for now since it appears to be an editor issue, but raised #28 which should fix this issue)
