### ISSUE TITLE
Document the configuration schema

### ISSUE THREAD

**Issue by ihabunek** [elixir-lsp/elixir-ls#309]
It took me a long time to find the available config options since they don't seem to be defined anywhere inside this project. Finally found them in the sibling project.
https://github.com/elixir-lsp/ide-elixir/blob/master/package.json#L12

Since this is a standalone project, it would be very nice to have the configuration defined in the README.

In the long term, have you considered setting up a docs website similar to https://erlang-ls.github.io/? It would be relatively easy to set up, I would be willing to help if you're interested.

**Comment by axelson** [comment]
Thanks, that is an oversight. Although elixir-ls/ide-elixir isn't the best place to look currently, the VSCode extension configuration settings are more up to date: https://github.com/elixir-lsp/vscode-elixir-ls/blob/99f3e238657ce045dfa952965222360e225d8abc/package.json#L49 is more 

I'll plan to add better documentation of the configuration options in #226 (which I'm am actively working on, albeit slowly)

I'm not too keen on setting up a docs website because I think it can very easily and quickly become out of date. I'd rather have a few more `.md` files in the repository with some links between them first. But thanks for the offer :)

**Comment by lukaszsamson** [comment]
Addressed in https://github.com/elixir-lsp/elixir-ls/commit/06e1dc0f2096b2245fcd5818f88e884c56e04823

**Comment by ihabunek** [comment]
Thank you!
