### ISSUE TITLE
"Go to Definition" does not work with umbrella apps

### ISSUE THREAD

**Issue by Nezteb** [elixir-lsp/elixir-ls#514]
### Environment

* Elixir & Erlang versions (elixir --version): 
  * Erlang/OTP 22.3.4.12
  * Elixir 1.8.1
* Operating system:
  * OS X 10.15.7
* Editor or IDE name (e.g. Emacs/VSCode):
  * VS Code
* Editor Plugin/LSP Client name:
  * https://github.com/elixir-lsp/vscode-elixir-ls

In this example, I'm trying to "Go to Definition" on Phoenix's `render` function, which is being used within an umbrella app:
<img width="343" alt="Screen Shot 2021-03-15 at 9 18 00 PM" src="https://user-images.githubusercontent.com/3588798/111246435-3ee9c200-85d4-11eb-9ba9-b444b25d8dab.png">

I'd expect it to bring me to the `deps/phoenix` folder like so:
<img width="701" alt="Screen Shot 2021-03-15 at 9 18 52 PM" src="https://user-images.githubusercontent.com/3588798/111246555-75274180-85d4-11eb-9dcf-a1a0e23be116.png">

In 2017, @JakeBecker said that umbrella apps are not supported: https://github.com/JakeBecker/vscode-elixir-ls/issues/6#issuecomment-308650563

I've searched this repo as well as the VS Code extension repo, and umbrella app support doesn't seem to be listed anywhere on any roadmap. The lack of support for umbrella apps also isn't listed in either project's `README`. There are some old issues for both projects that loosely touch on this subject, but they never explicitly call out the lack of "Go to Definition" support, so I figured I'd create this one until someone can decide what the best thing to do is.

**Comment by axelson** [comment]
Hi :wave:!, thanks for the report! Umbrella applications are expected to be fully supported. It looks like you are running into https://github.com/elixir-lsp/elixir-ls/issues/193 since that render function is actually a phoenix function imported by the `use` statement: https://hexdocs.pm/phoenix/Phoenix.Controller.html?#render/3

I'm going to close this for now, but if you find other issues specific to umbrellas, then please file a new issue.
