### ISSUE TITLE
Is it possible auto complete from module attribute that store module name?

### ISSUE THREAD

**Issue by iporsut** [elixir-lsp/elixir-ls#519]
I use lot Mox library to configure real and mock module for testing by using module attribute.

e.g.

```elixir
defmodule FileStorage do
  @callback download(path :: binary()) :: binary()
end
```

```elixir
defmodule Repository do
  @storage Application.compile_env!(:app,  FileStorage)
  def download(path) do
    @storage.download(path)
  end
end
```

`test.exs`
```elixir
config :app, FileStorge, FileStorage.Mock
```

I would like to know that possible elixir-ls auto complete and list function from module that store in attribute `@storage` when I type `@storage.`.

**Comment by axelson** [comment]
Hi @iporsut, unfortunately that's not currently possible. It might be theoretically possible, it would be difficult to know the value of `@storage` within ElixirLS. Someone could investigate the feasibility of it, but I'd be worried about potential edge cases and issues.

**Comment by lukaszsamson** [comment]
For it to work elixir-ls (or rather elixir_sense) would need to load configs from the client project (we already load applications so it could work) and eval client code inside elixir-ls process. Instead of evaling we also could parse expression AST, but it will only cover simple cases. @iporsut If you came up with a proof of concept we could consider it.
