### ISSUE TITLE
Support for textDocument/selectionRange API

### ISSUE THREAD

**Issue by aarongraham** [elixir-lsp/elixir-ls#534]
I recently moved to VSCode from IntelliJ, mostly because of ElixirLS, one feature I really miss however is the intelligent extend/shrink selection of text. VSCode has an [API available][1] for language servers to use to achieve the same thing. The [JSON extension][2] can be used as an implementation example. 

I would love to contribute to the extension by adding this feature if I could be pointed in the right direction? Or would adding this feature be a herculean task?

[1]: https://code.visualstudio.com/updates/v1_33#_smart-select-api
[2]: https://github.com/microsoft/vscode-json-languageservice/blob/db832ca6a9dec1693f70af575003e3beb34100d0/src/services/jsonSelectionRanges.ts#L11

**Comment by axelson** [comment]
Hi :wave:,

The Language Server Protocol version of that is `textDocument/selectionRange` (docs are at https://microsoft.github.io/language-server-protocol/specification#textDocument_selectionRange, and original discussion was at https://github.com/Microsoft/language-server-protocol/issues/613)

We would gladly merge well-written support for selectionRange. I wouldn't call this feature herculean, but it is a sizeable amount of work. For the syntax analysis the textDocument/foldingRange PR https://github.com/elixir-lsp/elixir-ls/pull/492 would be useful to look at.

I transferred this to the elixir-ls repo since it fits better there (and re-named the title).

**Comment by crispinb** [comment]
@aarongraham Are you currently working on this? If not, I'd be interested in picking it up (it's a feature I want!). 
@axelson - are you still open to a PR on this if I can pull it together (an 'if', as I don't really have the elixir chops)?

**Comment by aarongraham** [comment]
Hey @crispinb, I am not currently working on this no, life changed for me in a way that I have very little free time for coding outside of work now. I spent a decent amount of time thinking about how to achieve this early last year though. First I tried using `ElixirSense.Core.Normalized.Tokenizer.tokenize()`, however quickly realized that just getting the tokens was not enough, for the feature to work properly you need access to the whole syntax tree, or at least you need to know which tokens 'surround' the current cursor, as you basically want to highlight tokens as you walk up the tree. I remember struggling a lot with trying to figure out exactly where (line and character) tokens ended, this might be easier now with some of the additions that landed in Elixir 1.13 or using [Sourcerer](https://github.com/doorgan/sourceror). 

As a side note I recently switched to Neovim and now use tree-sitter alongside ElixirLS. The incremental selection offered in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) works great, even better than it did in IntelliJ in my opinion, and has support for basically every language. 

Good luck if you decide to have a go adding the feature, I'll definitely keep an eye out and be interested in seeing what you come up with.

**Comment by crispinb** [comment]
Thanks @aarongraham  - if I was writing a standalone VSCode extension, I'd consider tree-sitter because the api looks nice. As it is, I guess it wouldn't be a good fit for elixir-ls because of the required binary. And in any case part of my motivation  is to deepen my Elixir understanding.

I spent a bit of time this week reading up on the Elixir AST and looking through some relevant codebases, and came to about the same conclusion - ie. that this is essentially an exercise in walking up the AST, with ElixirSense probably useful for filling in holes resulting from the AST's lossiness. Thanks for the Sourcerer pointer.

**Comment by lukaszsamson** [comment]
Selection ranges provider added in https://github.com/elixir-lsp/elixir-ls/pull/1060. This turned out to be pretty big one. I tried 3 different approaches to that in the last years and none was satisfactory. Trying several different approaches at once and combining results as in folding ranges provider turned ot to work reasonably well. I'm going to release it in v0.20
