### ISSUE TITLE
Add support for a configuration file

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#60]
This is in addition to the `workspace/didChangeConfiguration` option.

Could look at https://github.com/erlang-ls/erlang_ls/pull/61 for inspiration

**Comment by znorris** [comment]
I've run into a case where I believe adding support for a configuration file would prove helpful. 

I recently resolved an issue where `:yamerl` was incorrectly throwing an error while I was debugging my application. The fix was adding an `excludedModules` key to the Elixir LS configuration. (Thanks for having the note about NIFs in the README)

```json
"excludeModules": [
    ":yamerl"
]
```

Being able to exclude this any time the project is running Elixir LS would be very helpful as it will give a deliberate place to share this knowledge among other developers.

I'm using the VS Code extension which allows me to save the exclusion in our repo via the `.vscode/launch.json` file. However, the exclusion has to be duplicated among VS Code launch configurations, and obviously it won't be available to non VS Code devs.

Thanks for what you do! 🥳

**Comment by lukaszsamson** [comment]
I don't see much value in having a separate config mechanism.
