### ISSUE TITLE
ElixirLS compiles without OTP EEP48 docs

### ISSUE THREAD

**Issue by veljkostevic2** [elixir-lsp/elixir-ls#794]
### Environment

* Elixir & Erlang versions (elixir --version):  Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Elixir Language Server version: [25dc8f0](https://github.com/elixir-lsp/elixir-ls/commit/25dc8f0a39fe158c1593749692d33e85f796c5c5)
* Operating system: Arch Linux x86_64

### Current behavior

ElixirLS can't compile correctly. It compiles without EEP48 documentation.
I followed guide on ElixirLS installation, but I can't make it work.
Erlang and elixir are installed with asdf.
Thanks for feedback.

```json
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS v0.12.0","type":3}}

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"ElixirLS built with elixir \"1.14.2\" on OTP \"25\"","type":3}}

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running on elixir \"1.14.2 (compiled with Erlang/OTP 25)\" on OTP \"25\"","type":3}}

{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"OTP compiled without EEP48 documentation chunks","type":2}}

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"OTP compiled without EEP48 documentation chunks. Language features for erlang modules will run in limited mode. Please reinstall or rebuild OTP with approperiate flags.","type":2}}

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Elixir sources not found (checking in /home/build/elixir). Code navigation to Elixir modules disabled.","type":3}}
```

### Expected behavior

Server should start successfully, without errors.

**Comment by lukaszsamson** [comment]
Please use forum or stackoverflow for support

**Comment by viniarck** [comment]
@veljkostevic2, I've also recently run into this same problem recently.

When I had the issue, I noticed that the `module_info/1` `[:compile][:source]` had a non existing directory, that's why the lsp couldn't find certain Elixir sources:

```
iex(1)> Enum.module_info()[:compile][:source]
'/home/build/elixir/lib/elixir/lib/enum.ex'
```

I managed to solve it by building elixir from source. Check out this comment below:

https://github.com/elixir-lsp/elixir_sense/issues/44#issuecomment-962615809

Once it's installed correctly with `asdf`, `module_info/1` `[:compile][:source]` should point out correctly to the source file:

```
iex(1)> Enum.module_info()[:compile][:source]
'/home/viniarck/repos/elixir/lib/elixir/lib/enum.ex'
```
