### ISSUE TITLE
Server hangs when a request sent to client isn't responded to. Is it intended behaviour?

### ISSUE THREAD

**Issue by yastanotheruser** [elixir-lsp/elixir-ls#847]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Elixir Language Server version: 0.13.0
* Operating system: Arch Linux, Linux kernel 6.2.6-arch1-1
* Editor or IDE name (e.g. Emacs/VSCode): Emacs
* Editor Plugin/LSP Client name and version: lsp-mode version 20230315.1114

### Current behavior

I'm using Emacs LSP mode and the ElixirLS client isn't working for me. It seems lsp-mode doesn't respond to a `client/registerCapability` request, which causes the `Server` process to hang in the `add_watched_extensions` function.

Logs:

```
Started ElixirLS v0.13.0
ElixirLS built with elixir "1.14.3" on OTP "25"
Running on elixir "1.14.3 (compiled with Erlang/OTP 25)" on OTP "25"
Elixir sources not found (checking in /home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.
```

Exchange (logs omitted):

https://pastebin.com/91YShmUX

### Expected behavior

Should the server continue serving requests?

**Comment by lukaszsamson** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_registerCapability

This is a required lifecycle request since LSP 3.0.

> Not all clients need to support dynamic capability registration. A client opts in via the dynamicRegistration property on the specific client capabilities

But in your pastebin I can see that the client advertises support for dynamic registration
```
"capabilities": {
  "workspace": {
    "didChangeWatchedFiles": {
      "dynamicRegistration": true
    }
  }
}
```

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles

> It is recommended that servers register for these file system events using the registration mechanism

And we do as recommended sending `client/registerCapability`

The client is required to return a response, see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage

> If a request doesn’t provide a result value the receiver of a request still needs to return a response message to conform to the JSON-RPC specification

The protocol requires client to return the following response

Response:
- result: void.
- error: code and message set in case an exception happens during the request.

So we are dealing with a non conforming client.

My advise is to report this issue to LSP mode repo.
