### ISSUE TITLE
Simplify launch script

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#945]
Options:
- remove relaunching: ASDF seems to work from POSIX shell (at least on macOS)
- keep relaunch but decide between bash and zsh based on `basename "$SHELL"`

**Comment by megalithic** [comment]
Love this, as I've had to move to lexical due to the requirement for asdf (i use rtx for lib management). they have a quick little detection script to detect which to use (though, i'd rather it check for binary, rather than a directory existing, so for now, i just delete ~/.asdf): https://github.com/lexical-lsp/lexical/blob/main/rel/deploy/overlays/start_lexical.sh

**Comment by lukaszsamson** [comment]
@megalithic a PR adding support for rtx would be welcome
